services:
  cognee:
    container_name: cognee
    restart: always
    networks:
      - cognee-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cognee:/app/cognee
      - .logs:/app/logs
      - .env:/app/.env
    environment:
      - DEBUG=false # Change to true if debugging
      - HOST=0.0.0.0
      - ENVIRONMENT=local
      - LOG_LEVEL=ERROR
    extra_hosts:
      # Allows the container to reach your local machine using "host.docker.internal" instead of "localhost"
      - "host.docker.internal:host-gateway"
    ports:
      - "9876:8000"

networks:
  cognee-network:
    name: cognee-network
#    external: true
